# Generated by Django 6.0.1 on 2026-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("reservation_data", models.DateField()),
                ("reservation_slot", models.SmallIntegerField(default=10)),
            ],
        ),
    ]
