# Generated by Django 6.0.1 on 2026-01-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="reservation_slot",
            new_name="N_personas",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="reservation_data",
            new_name="dia_de_reserva",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="first_name",
            new_name="nombre",
        ),
    ]
