# Generated by Django 6.0.1 on 2026-01-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0002_rename_reservation_slot_booking_n_personas_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="N_personas",
            new_name="n_personas",
        ),
    ]
