# Generated by Django 6.0.1 on 2026-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0003_rename_n_personas_booking_n_personas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="n_personas",
            new_name="n_de_personas",
        ),
        migrations.AddField(
            model_name="booking",
            name="fecha_de_reserva",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
