# Generated by Django 6.0.1 on 2026-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0004_menu_rename_n_personas_booking_n_de_personas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="fecha_de_reserva",
        ),
        migrations.AddField(
            model_name="booking",
            name="hora_de_reserva",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
